version: "3.1"
networks:
  app-tier:
    driver: bridge
services:
  mysql:
    networks:
      - app-tier
    image: "mysql/mysql-server:8.0"
    container_name: mysql_container_plain
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env

  nodejs:
    environment:
      MYSQL_HOST_IP: mysql # the name of mysql service in your docker-compose, which will get resolved to the internal IP of the mysql container
      DB_HOSTNAME: mysql
    networks:
      - app-tier
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - "5000:5000"
    links:
      - mysql
    depends_on:
      - mysql
    container_name: plain_server
    volumes:
      - ./:/usr/src/app